// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // TEMPORARY DIAGNOSTIC — remove once the "Invalid API key" issue is confirmed fixed.
  // The URL is not sensitive; the key is only shown as length + first 5 chars.
  if (typeof window !== "undefined") {
    console.info(
      "[Supabase debug] URL source:",
      import.meta.env.VITE_SUPABASE_URL ? "VITE_SUPABASE_URL" : "process.env.SUPABASE_URL",
    );
    console.info("[Supabase debug] URL value:", SUPABASE_URL);
    console.info(
      "[Supabase debug] KEY source:",
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
        ? "VITE_SUPABASE_PUBLISHABLE_KEY"
        : "process.env.SUPABASE_PUBLISHABLE_KEY",
    );
    console.info(
      "[Supabase debug] KEY length:",
      SUPABASE_PUBLISHABLE_KEY.length,
      "| first 5 chars:",
      SUPABASE_PUBLISHABLE_KEY.slice(0, 5),
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
